
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec 30 2025 14:26:40 IST (Dec 30 2025 08:56:40 UTC)

// Verification Directory fv/sync_fifo 

module sync_fifo(clk, rst_n, we, data_i, full, re, data_o, empty);
  input clk, rst_n, we, re;
  input [7:0] data_i;
  output full, empty;
  output [7:0] data_o;
  wire clk, rst_n, we, re;
  wire [7:0] data_i;
  wire full, empty;
  wire [7:0] data_o;
  wire [7:0] \fifo[15] ;
  wire [7:0] \fifo[12] ;
  wire [7:0] \fifo[13] ;
  wire [7:0] \fifo[14] ;
  wire [7:0] \fifo[11] ;
  wire [7:0] \fifo[8] ;
  wire [7:0] \fifo[9] ;
  wire [7:0] \fifo[10] ;
  wire [7:0] \fifo[6] ;
  wire [7:0] \fifo[7] ;
  wire [7:0] \fifo[3] ;
  wire [7:0] \fifo[0] ;
  wire [7:0] \fifo[1] ;
  wire [7:0] \fifo[2] ;
  wire [7:0] \fifo[4] ;
  wire [7:0] \fifo[5] ;
  wire [4:0] w_ptr;
  wire [4:0] r_ptr;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2, n_1, n_2,
       n_3, n_4;
  wire n_5, n_6, n_8, n_9, n_11, n_12, n_13, n_14;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_31, n_32, n_33;
  wire n_34, n_35, n_36, n_37, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_46, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_59, n_60;
  wire n_61, n_62, n_63, n_64, n_65, n_66, n_67, n_68;
  wire n_69, n_70, n_71, n_72, n_73, n_75, n_76, n_77;
  wire n_78, n_79, n_80, n_81, n_83, n_84, n_85, n_86;
  wire n_87, n_88, n_89, n_90, n_91, n_92, n_93, n_94;
  wire n_95, n_96, n_97, n_98, n_99, n_100, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_113, n_114, n_115, n_116, n_117, n_118, n_119;
  wire n_120, n_121, n_122, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_135;
  wire n_136, n_137, n_138, n_139, n_140, n_141, n_142, n_143;
  wire n_144, n_145, n_146, n_147, n_148, n_149, n_150, n_151;
  wire n_152, n_153, n_154, n_155, n_156, n_157, n_158, n_159;
  wire n_160, n_161, n_162, n_163, n_164, n_165, n_166, n_167;
  wire n_168, n_169, n_170, n_171, n_172, n_173, n_174, n_175;
  wire n_176, n_177, n_178, n_179, n_180, n_181, n_182, n_183;
  wire n_184, n_185, n_186, n_187, n_188, n_189, n_190, n_191;
  wire n_192, n_193, n_194, n_195, n_196, n_197, n_198, n_199;
  wire n_200, n_201, n_202, n_203, n_204, n_205, n_206, n_207;
  wire n_208, n_209, n_210, n_211, n_212, n_213, n_214, n_215;
  wire n_216, n_217, n_218, n_219, n_220, n_221, n_222, n_223;
  wire n_224, n_225, n_226, n_227, n_228, n_229, n_230, n_231;
  wire n_232, n_233, n_234, n_235, n_236, n_237, n_238, n_239;
  wire n_240, n_241, n_242, n_243, n_244, n_245, n_246, n_247;
  wire n_248, n_249, n_250, n_251, n_252, n_253, n_254, n_255;
  wire n_256, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_272;
  wire n_273, n_274, n_275, n_276, n_277, n_278, n_279, n_280;
  wire n_281, n_282, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352;
  wire n_353, n_354, n_355, n_356, n_357, n_358, n_359, n_360;
  wire n_361, n_362, n_363, n_364, n_365, n_366, n_367, n_368;
  wire n_369, n_370, n_372, n_373, n_374, n_375, n_376, n_377;
  wire n_378, n_379, n_380, n_381, n_382, n_383, n_384, n_385;
  wire n_386, n_387, n_388, n_389, n_390, n_391, n_392, n_393;
  wire n_394, n_395, n_396, n_397, n_398, n_399, n_400, n_401;
  wire n_402, n_403, n_404, n_405, n_406, n_407, n_408, n_409;
  wire n_410, n_411, n_412, n_413, n_414, n_415, n_416, n_417;
  wire n_418, n_419, n_420, n_421, n_422, n_423, n_424, n_425;
  wire n_426, n_427, n_428, n_429, n_430, n_431, n_432, n_433;
  wire n_434, n_435, n_436, n_437, n_438, n_439, n_440, n_441;
  wire n_442, n_443, n_444, n_445, n_446, n_447, n_448, n_449;
  wire n_450, n_451, n_452, n_453, n_454, n_455, n_456, n_457;
  wire n_458, n_459, n_460, n_461, n_462, n_463, n_464, n_465;
  wire n_466, n_467, n_468, n_469, n_470, n_471, n_472, n_473;
  wire n_474, n_475, n_476, n_477, n_478, n_479, n_480, n_481;
  wire n_482, n_483, n_484, n_497, n_498, n_499, n_500, n_501;
  wire n_502;
  DFFHQX1 \data_o_reg[0] (.CK (clk), .D (n_484), .Q (data_o[0]));
  DFFHQX1 \data_o_reg[1] (.CK (clk), .D (n_483), .Q (data_o[1]));
  DFFHQX1 \data_o_reg[3] (.CK (clk), .D (n_477), .Q (data_o[3]));
  DFFHQX1 \data_o_reg[4] (.CK (clk), .D (n_482), .Q (data_o[4]));
  DFFHQX1 \data_o_reg[5] (.CK (clk), .D (n_481), .Q (data_o[5]));
  DFFHQX1 \data_o_reg[2] (.CK (clk), .D (n_480), .Q (data_o[2]));
  DFFHQX1 \data_o_reg[6] (.CK (clk), .D (n_479), .Q (data_o[6]));
  DFFHQX1 \data_o_reg[7] (.CK (clk), .D (n_478), .Q (data_o[7]));
  INVX1 g10741(.A (n_471), .Y (n_484));
  INVX1 g10743(.A (n_476), .Y (n_483));
  INVX1 g10742(.A (n_473), .Y (n_482));
  INVX1 g10744(.A (n_470), .Y (n_481));
  INVX1 g10751(.A (n_472), .Y (n_480));
  INVX1 g10750(.A (n_475), .Y (n_479));
  INVX1 g10749(.A (n_468), .Y (n_478));
  INVX1 g10752(.A (n_469), .Y (n_477));
  AOI211XL g10747__2398(.A0 (\fifo[15] [1]), .A1 (n_474), .B0 (n_378),
       .C0 (n_467), .Y (n_476));
  AOI211XL g10754__5107(.A0 (\fifo[15] [6]), .A1 (n_474), .B0 (n_420),
       .C0 (n_465), .Y (n_475));
  AOI211XL g10746__6260(.A0 (\fifo[15] [4]), .A1 (n_474), .B0 (n_375),
       .C0 (n_464), .Y (n_473));
  AOI211XL g10755__4319(.A0 (\fifo[15] [2]), .A1 (n_474), .B0 (n_466),
       .C0 (n_424), .Y (n_472));
  AOI211XL g10745__8428(.A0 (\fifo[15] [0]), .A1 (n_474), .B0 (n_383),
       .C0 (n_462), .Y (n_471));
  AOI211XL g10748__5526(.A0 (\fifo[15] [5]), .A1 (n_474), .B0 (n_460),
       .C0 (n_390), .Y (n_470));
  AOI211XL g10756__6783(.A0 (\fifo[15] [3]), .A1 (n_474), .B0 (n_461),
       .C0 (n_377), .Y (n_469));
  AOI211XL g10753__3680(.A0 (\fifo[15] [7]), .A1 (n_474), .B0 (n_463),
       .C0 (n_422), .Y (n_468));
  DFFHQX1 \fifo_reg[12][6] (.CK (clk), .D (n_428), .Q (\fifo[12] [6]));
  DFFHQX1 \fifo_reg[13][0] (.CK (clk), .D (n_429), .Q (\fifo[13] [0]));
  DFFHQX1 \fifo_reg[15][1] (.CK (clk), .D (n_449), .Q (\fifo[15] [1]));
  DFFHQX1 \fifo_reg[15][2] (.CK (clk), .D (n_459), .Q (\fifo[15] [2]));
  DFFHQX1 \fifo_reg[15][3] (.CK (clk), .D (n_458), .Q (\fifo[15] [3]));
  DFFHQX1 \fifo_reg[15][4] (.CK (clk), .D (n_457), .Q (\fifo[15] [4]));
  DFFHQX1 \fifo_reg[15][5] (.CK (clk), .D (n_456), .Q (\fifo[15] [5]));
  DFFHQX1 \fifo_reg[15][6] (.CK (clk), .D (n_455), .Q (\fifo[15] [6]));
  DFFHQX1 \fifo_reg[15][7] (.CK (clk), .D (n_454), .Q (\fifo[15] [7]));
  DFFHQX1 \fifo_reg[12][0] (.CK (clk), .D (n_437), .Q (\fifo[12] [0]));
  DFFHQX1 \fifo_reg[12][1] (.CK (clk), .D (n_443), .Q (\fifo[12] [1]));
  DFFHQX1 \fifo_reg[12][2] (.CK (clk), .D (n_444), .Q (\fifo[12] [2]));
  DFFHQX1 \fifo_reg[12][3] (.CK (clk), .D (n_445), .Q (\fifo[12] [3]));
  DFFHQX1 \fifo_reg[12][4] (.CK (clk), .D (n_447), .Q (\fifo[12] [4]));
  DFFHQX1 \fifo_reg[12][5] (.CK (clk), .D (n_451), .Q (\fifo[12] [5]));
  DFFHQX1 \fifo_reg[14][0] (.CK (clk), .D (n_438), .Q (\fifo[14] [0]));
  DFFHQX1 \fifo_reg[15][0] (.CK (clk), .D (n_432), .Q (\fifo[15] [0]));
  DFFHQX1 \fifo_reg[13][1] (.CK (clk), .D (n_452), .Q (\fifo[13] [1]));
  DFFHQX1 \fifo_reg[13][2] (.CK (clk), .D (n_446), .Q (\fifo[13] [2]));
  DFFHQX1 \fifo_reg[13][3] (.CK (clk), .D (n_442), .Q (\fifo[13] [3]));
  DFFHQX1 \fifo_reg[13][5] (.CK (clk), .D (n_441), .Q (\fifo[13] [5]));
  DFFHQX1 \fifo_reg[13][6] (.CK (clk), .D (n_440), .Q (\fifo[13] [6]));
  DFFHQX1 \fifo_reg[13][7] (.CK (clk), .D (n_439), .Q (\fifo[13] [7]));
  DFFHQX1 \fifo_reg[13][4] (.CK (clk), .D (n_430), .Q (\fifo[13] [4]));
  DFFHQX1 \fifo_reg[14][1] (.CK (clk), .D (n_436), .Q (\fifo[14] [1]));
  DFFHQX1 \fifo_reg[14][2] (.CK (clk), .D (n_435), .Q (\fifo[14] [2]));
  DFFHQX1 \fifo_reg[14][3] (.CK (clk), .D (n_448), .Q (\fifo[14] [3]));
  DFFHQX1 \fifo_reg[14][4] (.CK (clk), .D (n_434), .Q (\fifo[14] [4]));
  DFFHQX1 \fifo_reg[14][5] (.CK (clk), .D (n_450), .Q (\fifo[14] [5]));
  DFFHQX1 \fifo_reg[14][6] (.CK (clk), .D (n_433), .Q (\fifo[14] [6]));
  DFFHQX1 \fifo_reg[14][7] (.CK (clk), .D (n_431), .Q (\fifo[14] [7]));
  DFFHQX1 \fifo_reg[12][7] (.CK (clk), .D (n_453), .Q (\fifo[12] [7]));
  NAND4X1 g10763__1617(.A (n_345), .B (n_215), .C (n_342), .D (n_208),
       .Y (n_467));
  NAND4X1 g10768__2802(.A (n_226), .B (n_231), .C (n_158), .D (n_253),
       .Y (n_466));
  NAND4X1 g10767__1705(.A (n_252), .B (n_258), .C (n_141), .D (n_248),
       .Y (n_465));
  DFFHQX1 \fifo_reg[11][5] (.CK (clk), .D (n_394), .Q (\fifo[11] [5]));
  DFFHQX1 \fifo_reg[8][0] (.CK (clk), .D (n_419), .Q (\fifo[8] [0]));
  DFFHQX1 \fifo_reg[8][1] (.CK (clk), .D (n_417), .Q (\fifo[8] [1]));
  DFFHQX1 \fifo_reg[8][2] (.CK (clk), .D (n_416), .Q (\fifo[8] [2]));
  DFFHQX1 \fifo_reg[8][3] (.CK (clk), .D (n_415), .Q (\fifo[8] [3]));
  DFFHQX1 \fifo_reg[8][5] (.CK (clk), .D (n_413), .Q (\fifo[8] [5]));
  DFFHQX1 \fifo_reg[8][6] (.CK (clk), .D (n_412), .Q (\fifo[8] [6]));
  DFFHQX1 \fifo_reg[8][7] (.CK (clk), .D (n_411), .Q (\fifo[8] [7]));
  DFFHQX1 \fifo_reg[9][1] (.CK (clk), .D (n_427), .Q (\fifo[9] [1]));
  DFFHQX1 \fifo_reg[9][2] (.CK (clk), .D (n_408), .Q (\fifo[9] [2]));
  DFFHQX1 \fifo_reg[9][3] (.CK (clk), .D (n_407), .Q (\fifo[9] [3]));
  DFFHQX1 \fifo_reg[9][5] (.CK (clk), .D (n_367), .Q (\fifo[9] [5]));
  DFFHQX1 \fifo_reg[9][6] (.CK (clk), .D (n_405), .Q (\fifo[9] [6]));
  DFFHQX1 \fifo_reg[9][7] (.CK (clk), .D (n_392), .Q (\fifo[9] [7]));
  DFFHQX1 \fifo_reg[11][4] (.CK (clk), .D (n_409), .Q (\fifo[11] [4]));
  DFFHQX1 \fifo_reg[10][1] (.CK (clk), .D (n_396), .Q (\fifo[10] [1]));
  DFFHQX1 \fifo_reg[11][7] (.CK (clk), .D (n_395), .Q (\fifo[11] [7]));
  NAND4X1 g10760__5122(.A (n_313), .B (n_216), .C (n_214), .D (n_132),
       .Y (n_464));
  NAND4X1 g10770__8246(.A (n_219), .B (n_220), .C (n_148), .D (n_222),
       .Y (n_463));
  NAND4X1 g10769__7098(.A (n_221), .B (n_238), .C (n_139), .D (n_277),
       .Y (n_462));
  NAND4X1 g10761__6131(.A (n_229), .B (n_240), .C (n_167), .D (n_257),
       .Y (n_461));
  NAND4X1 g10762__1881(.A (n_325), .B (n_341), .C (n_181), .D (n_334),
       .Y (n_460));
  DFFHQX1 \fifo_reg[11][2] (.CK (clk), .D (n_418), .Q (\fifo[11] [2]));
  DFFHQX1 \fifo_reg[11][3] (.CK (clk), .D (n_423), .Q (\fifo[11] [3]));
  DFFHQX1 \fifo_reg[11][6] (.CK (clk), .D (n_393), .Q (\fifo[11] [6]));
  DFFHQX1 \fifo_reg[9][4] (.CK (clk), .D (n_406), .Q (\fifo[9] [4]));
  DFFHQX1 \fifo_reg[11][0] (.CK (clk), .D (n_404), .Q (\fifo[11] [0]));
  DFFHQX1 \fifo_reg[10][4] (.CK (clk), .D (n_399), .Q (\fifo[10] [4]));
  DFFHQX1 \fifo_reg[10][6] (.CK (clk), .D (n_402), .Q (\fifo[10] [6]));
  DFFHQX1 \fifo_reg[10][0] (.CK (clk), .D (n_397), .Q (\fifo[10] [0]));
  DFFHQX1 \fifo_reg[9][0] (.CK (clk), .D (n_410), .Q (\fifo[9] [0]));
  DFFHQX1 \fifo_reg[8][4] (.CK (clk), .D (n_414), .Q (\fifo[8] [4]));
  DFFHQX1 \fifo_reg[10][2] (.CK (clk), .D (n_400), .Q (\fifo[10] [2]));
  DFFHQX1 \fifo_reg[10][3] (.CK (clk), .D (n_398), .Q (\fifo[10] [3]));
  DFFHQX1 \fifo_reg[10][5] (.CK (clk), .D (n_401), .Q (\fifo[10] [5]));
  DFFHQX1 \fifo_reg[10][7] (.CK (clk), .D (n_403), .Q (\fifo[10] [7]));
  DFFHQX1 \fifo_reg[11][1] (.CK (clk), .D (n_425), .Q (\fifo[11] [1]));
  INVX1 g10903(.A (n_389), .Y (n_459));
  INVX1 g10904(.A (n_386), .Y (n_458));
  INVX1 g10905(.A (n_385), .Y (n_457));
  INVX1 g10907(.A (n_384), .Y (n_456));
  INVX1 g10908(.A (n_382), .Y (n_455));
  INVX1 g10910(.A (n_376), .Y (n_454));
  INVX1 g11105(.A (n_364), .Y (n_453));
  INVX1 g11107(.A (n_362), .Y (n_452));
  INVX1 g11103(.A (n_366), .Y (n_451));
  INVX1 g10922(.A (n_374), .Y (n_450));
  INVX1 g10945(.A (n_426), .Y (n_449));
  INVX1 g11077(.A (n_381), .Y (n_448));
  INVX1 g11102(.A (n_391), .Y (n_447));
  DFFHQX1 \fifo_reg[6][0] (.CK (clk), .D (n_291), .Q (\fifo[6] [0]));
  DFFHQX1 \fifo_reg[7][4] (.CK (clk), .D (n_318), .Q (\fifo[7] [4]));
  DFFHQX1 \fifo_reg[7][6] (.CK (clk), .D (n_316), .Q (\fifo[7] [6]));
  DFFHQX1 \fifo_reg[7][5] (.CK (clk), .D (n_317), .Q (\fifo[7] [5]));
  DFFHQX1 \fifo_reg[6][4] (.CK (clk), .D (n_283), .Q (\fifo[6] [4]));
  DFFHQX1 \fifo_reg[3][5] (.CK (clk), .D (n_304), .Q (\fifo[3] [5]));
  DFFHQX1 \fifo_reg[0][5] (.CK (clk), .D (n_343), .Q (\fifo[0] [5]));
  DFFHQX1 \fifo_reg[0][6] (.CK (clk), .D (n_338), .Q (\fifo[0] [6]));
  DFFHQX1 \fifo_reg[7][0] (.CK (clk), .D (n_278), .Q (\fifo[7] [0]));
  DFFHQX1 \fifo_reg[0][7] (.CK (clk), .D (n_337), .Q (\fifo[0] [7]));
  DFFHQX1 \fifo_reg[1][0] (.CK (clk), .D (n_336), .Q (\fifo[1] [0]));
  DFFHQX1 \fifo_reg[1][1] (.CK (clk), .D (n_335), .Q (\fifo[1] [1]));
  DFFHQX1 \fifo_reg[1][2] (.CK (clk), .D (n_331), .Q (\fifo[1] [2]));
  DFFHQX1 \fifo_reg[1][3] (.CK (clk), .D (n_330), .Q (\fifo[1] [3]));
  DFFHQX1 \fifo_reg[1][5] (.CK (clk), .D (n_328), .Q (\fifo[1] [5]));
  DFFHQX1 \fifo_reg[1][7] (.CK (clk), .D (n_326), .Q (\fifo[1] [7]));
  DFFHQX1 \fifo_reg[2][1] (.CK (clk), .D (n_323), .Q (\fifo[2] [1]));
  DFFHQX1 \fifo_reg[2][2] (.CK (clk), .D (n_322), .Q (\fifo[2] [2]));
  DFFHQX1 \fifo_reg[2][3] (.CK (clk), .D (n_321), .Q (\fifo[2] [3]));
  DFFHQX1 \fifo_reg[2][5] (.CK (clk), .D (n_319), .Q (\fifo[2] [5]));
  DFFHQX1 \fifo_reg[2][6] (.CK (clk), .D (n_315), .Q (\fifo[2] [6]));
  DFFHQX1 \fifo_reg[2][7] (.CK (clk), .D (n_314), .Q (\fifo[2] [7]));
  DFFHQX1 \fifo_reg[3][1] (.CK (clk), .D (n_308), .Q (\fifo[3] [1]));
  DFFHQX1 \fifo_reg[3][2] (.CK (clk), .D (n_307), .Q (\fifo[3] [2]));
  DFFHQX1 \fifo_reg[3][3] (.CK (clk), .D (n_306), .Q (\fifo[3] [3]));
  DFFHQX1 \fifo_reg[0][4] (.CK (clk), .D (n_282), .Q (\fifo[0] [4]));
  DFFHQX1 \fifo_reg[3][7] (.CK (clk), .D (n_344), .Q (\fifo[3] [7]));
  DFFHQX1 \fifo_reg[4][1] (.CK (clk), .D (n_300), .Q (\fifo[4] [1]));
  DFFHQX1 \fifo_reg[4][2] (.CK (clk), .D (n_301), .Q (\fifo[4] [2]));
  DFFHQX1 \fifo_reg[4][3] (.CK (clk), .D (n_302), .Q (\fifo[4] [3]));
  DFFHQX1 \fifo_reg[4][5] (.CK (clk), .D (n_309), .Q (\fifo[4] [5]));
  DFFHQX1 \fifo_reg[4][6] (.CK (clk), .D (n_274), .Q (\fifo[4] [6]));
  DFFHQX1 \fifo_reg[4][7] (.CK (clk), .D (n_297), .Q (\fifo[4] [7]));
  DFFHQX1 \fifo_reg[5][1] (.CK (clk), .D (n_346), .Q (\fifo[5] [1]));
  DFFHQX1 \fifo_reg[5][2] (.CK (clk), .D (n_296), .Q (\fifo[5] [2]));
  INVX1 g11115(.A (n_353), .Y (n_446));
  INVX1 g11101(.A (n_368), .Y (n_445));
  INVX1 g11100(.A (n_369), .Y (n_444));
  INVX1 g11099(.A (n_370), .Y (n_443));
  INVX1 g11108(.A (n_359), .Y (n_442));
  INVX1 g11111(.A (n_357), .Y (n_441));
  INVX1 g11112(.A (n_356), .Y (n_440));
  INVX1 g11113(.A (n_355), .Y (n_439));
  INVX1 g11114(.A (n_354), .Y (n_438));
  INVX1 g11098(.A (n_373), .Y (n_437));
  INVX1 g11116(.A (n_352), .Y (n_436));
  INVX1 g11117(.A (n_351), .Y (n_435));
  INVX1 g11119(.A (n_350), .Y (n_434));
  INVX1 g11121(.A (n_349), .Y (n_433));
  INVX1 g11123(.A (n_348), .Y (n_432));
  INVX1 g10962(.A (n_421), .Y (n_431));
  INVX1 g11109(.A (n_358), .Y (n_430));
  INVX1 g11106(.A (n_363), .Y (n_429));
  INVX1 g11104(.A (n_365), .Y (n_428));
  DFFHQX1 \fifo_reg[3][4] (.CK (clk), .D (n_305), .Q (\fifo[3] [4]));
  DFFHQX1 \fifo_reg[3][0] (.CK (clk), .D (n_310), .Q (\fifo[3] [0]));
  DFFHQX1 \fifo_reg[2][4] (.CK (clk), .D (n_320), .Q (\fifo[2] [4]));
  DFFHQX1 \fifo_reg[1][6] (.CK (clk), .D (n_327), .Q (\fifo[1] [6]));
  DFFHQX1 \fifo_reg[5][5] (.CK (clk), .D (n_295), .Q (\fifo[5] [5]));
  DFFHQX1 \fifo_reg[2][0] (.CK (clk), .D (n_324), .Q (\fifo[2] [0]));
  DFFHQX1 \fifo_reg[1][4] (.CK (clk), .D (n_329), .Q (\fifo[1] [4]));
  DFFHQX1 \fifo_reg[5][7] (.CK (clk), .D (n_292), .Q (\fifo[5] [7]));
  DFFHQX1 \fifo_reg[4][0] (.CK (clk), .D (n_298), .Q (\fifo[4] [0]));
  DFFHQX1 \fifo_reg[0][1] (.CK (clk), .D (n_290), .Q (\fifo[0] [1]));
  DFFHQX1 \fifo_reg[5][6] (.CK (clk), .D (n_294), .Q (\fifo[5] [6]));
  DFFHQX1 \fifo_reg[0][3] (.CK (clk), .D (n_285), .Q (\fifo[0] [3]));
  DFFHQX1 \fifo_reg[6][1] (.CK (clk), .D (n_289), .Q (\fifo[6] [1]));
  DFFHQX1 \fifo_reg[6][2] (.CK (clk), .D (n_287), .Q (\fifo[6] [2]));
  DFFHQX1 \fifo_reg[6][3] (.CK (clk), .D (n_284), .Q (\fifo[6] [3]));
  DFFHQX1 \fifo_reg[6][5] (.CK (clk), .D (n_247), .Q (\fifo[6] [5]));
  DFFHQX1 \fifo_reg[6][6] (.CK (clk), .D (n_280), .Q (\fifo[6] [6]));
  DFFHQX1 \fifo_reg[6][7] (.CK (clk), .D (n_279), .Q (\fifo[6] [7]));
  DFFHQX1 \fifo_reg[5][3] (.CK (clk), .D (n_267), .Q (\fifo[5] [3]));
  DFFHQX1 \fifo_reg[7][1] (.CK (clk), .D (n_276), .Q (\fifo[7] [1]));
  DFFHQX1 \fifo_reg[7][2] (.CK (clk), .D (n_275), .Q (\fifo[7] [2]));
  DFFHQX1 \fifo_reg[7][3] (.CK (clk), .D (n_293), .Q (\fifo[7] [3]));
  DFFHQX1 \fifo_reg[7][7] (.CK (clk), .D (n_347), .Q (\fifo[7] [7]));
  DFFHQX1 \fifo_reg[5][0] (.CK (clk), .D (n_299), .Q (\fifo[5] [0]));
  DFFHQX1 \fifo_reg[5][4] (.CK (clk), .D (n_218), .Q (\fifo[5] [4]));
  DFFHQX1 \fifo_reg[0][2] (.CK (clk), .D (n_288), .Q (\fifo[0] [2]));
  DFFHQX1 \fifo_reg[0][0] (.CK (clk), .D (n_217), .Q (\fifo[0] [0]));
  DFFHQX1 \fifo_reg[4][4] (.CK (clk), .D (n_303), .Q (\fifo[4] [4]));
  DFFHQX1 \fifo_reg[3][6] (.CK (clk), .D (n_286), .Q (\fifo[3] [6]));
  INVXL g11074(.A (n_261), .Y (n_427));
  AOI22X1 g11029__5115(.A0 (\fifo[15] [1]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[1]), .Y (n_426));
  INVXL g11091(.A (n_234), .Y (n_425));
  NAND4X1 g10764__7482(.A (n_107), .B (n_91), .C (n_106), .D (n_119),
       .Y (n_424));
  INVXL g11093(.A (n_228), .Y (n_423));
  NAND4X1 g10765__4733(.A (n_96), .B (n_95), .C (n_97), .D (n_99), .Y
       (n_422));
  AOI22X1 g11055__6161(.A0 (\fifo[14] [7]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[7]), .Y (n_421));
  NAND4X1 g10766__9315(.A (n_122), .B (n_118), .C (n_103), .D (n_102),
       .Y (n_420));
  INVXL g11065(.A (n_273), .Y (n_419));
  INVXL g11092(.A (n_230), .Y (n_418));
  INVXL g11066(.A (n_272), .Y (n_417));
  INVXL g11067(.A (n_269), .Y (n_416));
  INVXL g11068(.A (n_268), .Y (n_415));
  INVXL g11069(.A (n_266), .Y (n_414));
  INVXL g11070(.A (n_265), .Y (n_413));
  INVXL g11071(.A (n_264), .Y (n_412));
  INVXL g11072(.A (n_263), .Y (n_411));
  INVXL g11073(.A (n_262), .Y (n_410));
  INVXL g11094(.A (n_227), .Y (n_409));
  INVXL g11075(.A (n_256), .Y (n_408));
  INVXL g11076(.A (n_255), .Y (n_407));
  INVXL g11078(.A (n_254), .Y (n_406));
  INVXL g11080(.A (n_250), .Y (n_405));
  INVXL g11090(.A (n_235), .Y (n_404));
  INVXL g11089(.A (n_236), .Y (n_403));
  INVXL g11088(.A (n_237), .Y (n_402));
  INVXL g11087(.A (n_239), .Y (n_401));
  INVXL g11084(.A (n_243), .Y (n_400));
  INVXL g11086(.A (n_241), .Y (n_399));
  INVXL g11085(.A (n_242), .Y (n_398));
  INVXL g11082(.A (n_281), .Y (n_397));
  INVXL g11083(.A (n_246), .Y (n_396));
  INVXL g11097(.A (n_223), .Y (n_395));
  INVXL g11095(.A (n_225), .Y (n_394));
  INVXL g11096(.A (n_224), .Y (n_393));
  INVXL g11081(.A (n_249), .Y (n_392));
  AOI22X1 g11190__9945(.A0 (\fifo[12] [4]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[4]), .Y (n_391));
  NAND4X1 g10757__2883(.A (n_111), .B (n_109), .C (n_114), .D (n_110),
       .Y (n_390));
  AOI22X1 g10967__2346(.A0 (\fifo[15] [2]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[2]), .Y (n_389));
  AOI22X1 g10968__1666(.A0 (\fifo[15] [3]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[3]), .Y (n_386));
  AOI22X1 g10970__7410(.A0 (\fifo[15] [4]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[4]), .Y (n_385));
  AOI22X1 g10972__6417(.A0 (\fifo[15] [5]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[5]), .Y (n_384));
  NAND4X1 g10771__5477(.A (n_123), .B (n_108), .C (n_90), .D (n_117),
       .Y (n_383));
  AOI22X1 g10974__2398(.A0 (\fifo[15] [6]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[6]), .Y (n_382));
  AOI22X1 g11151__5107(.A0 (\fifo[14] [3]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[3]), .Y (n_381));
  NAND4X1 g10758__6260(.A (n_86), .B (n_88), .C (n_98), .D (n_100), .Y
       (n_378));
  NAND4X1 g10772__4319(.A (n_92), .B (n_85), .C (n_84), .D (n_87), .Y
       (n_377));
  AOI22X1 g10976__8428(.A0 (\fifo[15] [7]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[7]), .Y (n_376));
  NAND4X1 g10759__5526(.A (n_89), .B (n_83), .C (n_94), .D (n_93), .Y
       (n_375));
  AOI22X1 g10992__6783(.A0 (\fifo[14] [5]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[5]), .Y (n_374));
  AOI22X1 g11184__3680(.A0 (\fifo[12] [0]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[0]), .Y (n_373));
  AOI22X1 g11186__1617(.A0 (\fifo[12] [1]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[1]), .Y (n_370));
  AOI22X1 g11187__2802(.A0 (\fifo[12] [2]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[2]), .Y (n_369));
  AOI22X1 g11188__1705(.A0 (\fifo[12] [3]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[3]), .Y (n_368));
  INVXL g11079(.A (n_251), .Y (n_367));
  AOI22X1 g11192__5122(.A0 (\fifo[12] [5]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[5]), .Y (n_366));
  AOI22X1 g11193__8246(.A0 (\fifo[12] [6]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[6]), .Y (n_365));
  AOI22X1 g11195__7098(.A0 (\fifo[12] [7]), .A1 (n_372), .B0 (n_502),
       .B1 (data_i[7]), .Y (n_364));
  AOI22X1 g11196__6131(.A0 (\fifo[13] [0]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[0]), .Y (n_363));
  AOI22X1 g11197__1881(.A0 (\fifo[13] [1]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[1]), .Y (n_362));
  AOI22X1 g11200__5115(.A0 (\fifo[13] [3]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[3]), .Y (n_359));
  AOI22X1 g11202__7482(.A0 (\fifo[13] [4]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[4]), .Y (n_358));
  AOI22X1 g11204__4733(.A0 (\fifo[13] [5]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[5]), .Y (n_357));
  AOI22X1 g11205__6161(.A0 (\fifo[13] [6]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[6]), .Y (n_356));
  AOI22X1 g11206__9315(.A0 (\fifo[13] [7]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[7]), .Y (n_355));
  AOI22X1 g11208__9945(.A0 (\fifo[14] [0]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[0]), .Y (n_354));
  AOI22X1 g11209__2883(.A0 (\fifo[13] [2]), .A1 (n_361), .B0 (n_360),
       .B1 (data_i[2]), .Y (n_353));
  AOI22X1 g11210__2346(.A0 (\fifo[14] [1]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[1]), .Y (n_352));
  AOI22X1 g11212__1666(.A0 (\fifo[14] [2]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[2]), .Y (n_351));
  AOI22X1 g11214__7410(.A0 (\fifo[14] [4]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[4]), .Y (n_350));
  AOI22X1 g11218__6417(.A0 (\fifo[14] [6]), .A1 (n_380), .B0 (n_379),
       .B1 (data_i[6]), .Y (n_349));
  AOI22X1 g11220__5477(.A0 (\fifo[15] [0]), .A1 (n_388), .B0 (n_387),
       .B1 (data_i[0]), .Y (n_348));
  INVX1 g11064(.A (n_175), .Y (n_347));
  INVX1 g10946(.A (n_205), .Y (n_346));
  AOI22X1 g11034__2398(.A0 (\fifo[14] [1]), .A1 (n_340), .B0
       (\fifo[13] [1]), .B1 (n_339), .Y (n_345));
  INVX1 g10901(.A (n_174), .Y (n_344));
  INVX1 g10902(.A (n_173), .Y (n_343));
  AOI22X1 g11046__5107(.A0 (\fifo[12] [1]), .A1 (n_333), .B0
       (\fifo[11] [1]), .B1 (n_332), .Y (n_342));
  AOI22X1 g11047__6260(.A0 (\fifo[14] [5]), .A1 (n_340), .B0
       (\fifo[13] [5]), .B1 (n_339), .Y (n_341));
  INVX1 g10906(.A (n_172), .Y (n_338));
  INVX1 g10909(.A (n_169), .Y (n_337));
  INVX1 g10911(.A (n_168), .Y (n_336));
  INVX1 g10912(.A (n_166), .Y (n_335));
  AOI22X1 g11052__4319(.A0 (\fifo[12] [5]), .A1 (n_333), .B0
       (\fifo[11] [5]), .B1 (n_332), .Y (n_334));
  INVX1 g10913(.A (n_160), .Y (n_331));
  INVX1 g10914(.A (n_159), .Y (n_330));
  INVX1 g10915(.A (n_157), .Y (n_329));
  INVX1 g10916(.A (n_156), .Y (n_328));
  INVX1 g10917(.A (n_155), .Y (n_327));
  INVX1 g10918(.A (n_154), .Y (n_326));
  AOI22X1 g11056__8428(.A0 (\fifo[10] [5]), .A1 (n_312), .B0
       (\fifo[9] [5]), .B1 (n_311), .Y (n_325));
  INVX1 g10919(.A (n_153), .Y (n_324));
  INVX1 g10920(.A (n_152), .Y (n_323));
  INVX1 g10921(.A (n_149), .Y (n_322));
  INVX1 g10923(.A (n_147), .Y (n_321));
  INVX1 g10924(.A (n_146), .Y (n_320));
  INVX1 g10925(.A (n_145), .Y (n_319));
  INVX1 g11061(.A (n_178), .Y (n_318));
  INVX1 g11062(.A (n_177), .Y (n_317));
  INVX1 g11063(.A (n_176), .Y (n_316));
  INVX1 g10926(.A (n_144), .Y (n_315));
  INVX1 g10927(.A (n_143), .Y (n_314));
  AOI22X1 g11022__5526(.A0 (\fifo[10] [4]), .A1 (n_312), .B0
       (\fifo[9] [4]), .B1 (n_311), .Y (n_313));
  INVX1 g10928(.A (n_163), .Y (n_310));
  INVX1 g10941(.A (n_212), .Y (n_309));
  INVX1 g10929(.A (n_140), .Y (n_308));
  INVX1 g10930(.A (n_138), .Y (n_307));
  INVX1 g10931(.A (n_136), .Y (n_306));
  INVX1 g10932(.A (n_133), .Y (n_305));
  INVX1 g10933(.A (n_130), .Y (n_304));
  INVX1 g10940(.A (n_189), .Y (n_303));
  INVX1 g10939(.A (n_124), .Y (n_302));
  INVX1 g10938(.A (n_125), .Y (n_301));
  INVX1 g10937(.A (n_126), .Y (n_300));
  INVX1 g10944(.A (n_206), .Y (n_299));
  INVX1 g10936(.A (n_127), .Y (n_298));
  INVX1 g10943(.A (n_207), .Y (n_297));
  INVX1 g10947(.A (n_202), .Y (n_296));
  INVX1 g10950(.A (n_199), .Y (n_295));
  INVX1 g10951(.A (n_198), .Y (n_294));
  INVX1 g10935(.A (n_128), .Y (n_293));
  INVX1 g10952(.A (n_197), .Y (n_292));
  INVX1 g10953(.A (n_196), .Y (n_291));
  INVX1 g11118(.A (n_137), .Y (n_290));
  INVX1 g10954(.A (n_193), .Y (n_289));
  INVX1 g11120(.A (n_135), .Y (n_288));
  INVX1 g10955(.A (n_192), .Y (n_287));
  INVX1 g10934(.A (n_129), .Y (n_286));
  INVX1 g11122(.A (n_134), .Y (n_285));
  INVX1 g10956(.A (n_191), .Y (n_284));
  INVX1 g10957(.A (n_190), .Y (n_283));
  INVX1 g11124(.A (n_131), .Y (n_282));
  AOI22XL g11159__6783(.A0 (\fifo[10] [0]), .A1 (n_245), .B0
       (data_i[0]), .B1 (n_244), .Y (n_281));
  INVX1 g10959(.A (n_188), .Y (n_280));
  INVX1 g10960(.A (n_187), .Y (n_279));
  INVX1 g10961(.A (n_186), .Y (n_278));
  AOI22X1 g11129__3680(.A0 (\fifo[12] [0]), .A1 (n_333), .B0
       (\fifo[11] [0]), .B1 (n_332), .Y (n_277));
  INVX1 g10963(.A (n_185), .Y (n_276));
  INVX1 g10964(.A (n_182), .Y (n_275));
  INVX1 g10942(.A (n_211), .Y (n_274));
  AOI22XL g11132__1617(.A0 (\fifo[8] [0]), .A1 (n_501), .B0
       (data_i[0]), .B1 (n_270), .Y (n_273));
  AOI22XL g11134__2802(.A0 (\fifo[8] [1]), .A1 (n_501), .B0
       (data_i[1]), .B1 (n_270), .Y (n_272));
  AOI22XL g11136__1705(.A0 (\fifo[8] [2]), .A1 (n_501), .B0
       (data_i[2]), .B1 (n_270), .Y (n_269));
  AOI22XL g11137__5122(.A0 (\fifo[8] [3]), .A1 (n_501), .B0
       (data_i[3]), .B1 (n_270), .Y (n_268));
  INVX1 g10948(.A (n_201), .Y (n_267));
  AOI22XL g11138__8246(.A0 (\fifo[8] [4]), .A1 (n_501), .B0
       (data_i[4]), .B1 (n_270), .Y (n_266));
  AOI22XL g11139__7098(.A0 (\fifo[8] [5]), .A1 (n_501), .B0
       (data_i[5]), .B1 (n_270), .Y (n_265));
  AOI22XL g11141__6131(.A0 (\fifo[8] [6]), .A1 (n_501), .B0
       (data_i[6]), .B1 (n_270), .Y (n_264));
  AOI22XL g11143__1881(.A0 (\fifo[8] [7]), .A1 (n_501), .B0
       (data_i[7]), .B1 (n_270), .Y (n_263));
  AOI22XL g11145__5115(.A0 (\fifo[9] [0]), .A1 (n_260), .B0
       (data_i[0]), .B1 (n_259), .Y (n_262));
  AOI22XL g11147__7482(.A0 (\fifo[9] [1]), .A1 (n_260), .B0
       (data_i[1]), .B1 (n_259), .Y (n_261));
  AOI22X1 g11148__4733(.A0 (\fifo[10] [6]), .A1 (n_312), .B0
       (\fifo[9] [6]), .B1 (n_311), .Y (n_258));
  AOI22X1 g10973__6161(.A0 (\fifo[12] [3]), .A1 (n_333), .B0
       (\fifo[11] [3]), .B1 (n_332), .Y (n_257));
  AOI22XL g11149__9315(.A0 (\fifo[9] [2]), .A1 (n_260), .B0
       (data_i[2]), .B1 (n_259), .Y (n_256));
  AOI22XL g11150__9945(.A0 (\fifo[9] [3]), .A1 (n_260), .B0
       (data_i[3]), .B1 (n_259), .Y (n_255));
  AOI22XL g11152__2883(.A0 (\fifo[9] [4]), .A1 (n_260), .B0
       (data_i[4]), .B1 (n_259), .Y (n_254));
  AOI22X1 g11153__2346(.A0 (\fifo[12] [2]), .A1 (n_333), .B0
       (\fifo[11] [2]), .B1 (n_332), .Y (n_253));
  AOI22X1 g11154__1666(.A0 (\fifo[14] [6]), .A1 (n_340), .B0
       (\fifo[13] [6]), .B1 (n_339), .Y (n_252));
  AOI22XL g11155__7410(.A0 (\fifo[9] [5]), .A1 (n_260), .B0
       (data_i[5]), .B1 (n_259), .Y (n_251));
  AOI22XL g11156__6417(.A0 (\fifo[9] [6]), .A1 (n_260), .B0
       (data_i[6]), .B1 (n_259), .Y (n_250));
  AOI22XL g11157__5477(.A0 (\fifo[9] [7]), .A1 (n_260), .B0
       (data_i[7]), .B1 (n_259), .Y (n_249));
  AOI22X1 g11158__2398(.A0 (\fifo[12] [6]), .A1 (n_333), .B0
       (\fifo[11] [6]), .B1 (n_332), .Y (n_248));
  INVX1 g10958(.A (n_213), .Y (n_247));
  AOI22XL g11160__5107(.A0 (\fifo[10] [1]), .A1 (n_245), .B0
       (data_i[1]), .B1 (n_244), .Y (n_246));
  AOI22XL g11162__6260(.A0 (\fifo[10] [2]), .A1 (n_245), .B0
       (data_i[2]), .B1 (n_244), .Y (n_243));
  AOI22XL g11163__4319(.A0 (\fifo[10] [3]), .A1 (n_245), .B0
       (data_i[3]), .B1 (n_244), .Y (n_242));
  AOI22XL g11164__8428(.A0 (\fifo[10] [4]), .A1 (n_245), .B0
       (data_i[4]), .B1 (n_244), .Y (n_241));
  AOI22X1 g10982__5526(.A0 (\fifo[14] [3]), .A1 (n_340), .B0
       (\fifo[13] [3]), .B1 (n_339), .Y (n_240));
  AOI22XL g11166__6783(.A0 (\fifo[10] [5]), .A1 (n_245), .B0
       (data_i[5]), .B1 (n_244), .Y (n_239));
  AOI22X1 g11167__3680(.A0 (\fifo[10] [0]), .A1 (n_312), .B0
       (\fifo[9] [0]), .B1 (n_311), .Y (n_238));
  AOI22XL g11168__1617(.A0 (\fifo[10] [6]), .A1 (n_245), .B0
       (data_i[6]), .B1 (n_244), .Y (n_237));
  AOI22XL g11169__2802(.A0 (\fifo[10] [7]), .A1 (n_245), .B0
       (data_i[7]), .B1 (n_244), .Y (n_236));
  AOI22XL g11171__1705(.A0 (\fifo[11] [0]), .A1 (n_233), .B0
       (data_i[0]), .B1 (n_232), .Y (n_235));
  AOI22XL g11172__5122(.A0 (\fifo[11] [1]), .A1 (n_233), .B0
       (data_i[1]), .B1 (n_232), .Y (n_234));
  AOI22X1 g11173__8246(.A0 (\fifo[14] [2]), .A1 (n_340), .B0
       (\fifo[13] [2]), .B1 (n_339), .Y (n_231));
  AOI22XL g11175__7098(.A0 (\fifo[11] [2]), .A1 (n_233), .B0
       (data_i[2]), .B1 (n_232), .Y (n_230));
  AOI22X1 g10987__6131(.A0 (\fifo[10] [3]), .A1 (n_312), .B0
       (\fifo[9] [3]), .B1 (n_311), .Y (n_229));
  AOI22XL g11176__1881(.A0 (\fifo[11] [3]), .A1 (n_233), .B0
       (data_i[3]), .B1 (n_232), .Y (n_228));
  AOI22XL g11178__5115(.A0 (\fifo[11] [4]), .A1 (n_233), .B0
       (data_i[4]), .B1 (n_232), .Y (n_227));
  AOI22X1 g11179__7482(.A0 (\fifo[10] [2]), .A1 (n_312), .B0
       (\fifo[9] [2]), .B1 (n_311), .Y (n_226));
  AOI22XL g11180__4733(.A0 (\fifo[11] [5]), .A1 (n_233), .B0
       (data_i[5]), .B1 (n_232), .Y (n_225));
  AOI22XL g11182__6161(.A0 (\fifo[11] [6]), .A1 (n_233), .B0
       (data_i[6]), .B1 (n_232), .Y (n_224));
  AOI22XL g11183__9315(.A0 (\fifo[11] [7]), .A1 (n_233), .B0
       (data_i[7]), .B1 (n_232), .Y (n_223));
  AOI22X1 g11185__9945(.A0 (\fifo[12] [7]), .A1 (n_333), .B0
       (\fifo[11] [7]), .B1 (n_332), .Y (n_222));
  AOI22X1 g11191__2883(.A0 (\fifo[14] [0]), .A1 (n_340), .B0
       (\fifo[13] [0]), .B1 (n_339), .Y (n_221));
  AOI22X1 g11194__2346(.A0 (\fifo[14] [7]), .A1 (n_340), .B0
       (\fifo[13] [7]), .B1 (n_339), .Y (n_220));
  AOI22X1 g11198__1666(.A0 (\fifo[10] [7]), .A1 (n_312), .B0
       (\fifo[9] [7]), .B1 (n_311), .Y (n_219));
  INVX1 g10949(.A (n_200), .Y (n_218));
  INVX1 g11110(.A (n_142), .Y (n_217));
  AOI22X1 g11014__7410(.A0 (\fifo[14] [4]), .A1 (n_340), .B0
       (\fifo[13] [4]), .B1 (n_339), .Y (n_216));
  AOI22X1 g11016__6417(.A0 (\fifo[10] [1]), .A1 (n_312), .B0
       (\fifo[9] [1]), .B1 (n_311), .Y (n_215));
  AOI22X1 g11018__5477(.A0 (\fifo[12] [4]), .A1 (n_333), .B0
       (\fifo[11] [4]), .B1 (n_332), .Y (n_214));
  AOI22X1 g11049__2398(.A0 (\fifo[6] [5]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[5]), .Y (n_213));
  AOI22X1 g11023__5107(.A0 (\fifo[4] [5]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[5]), .Y (n_212));
  AOI22X1 g11024__6260(.A0 (\fifo[4] [6]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[6]), .Y (n_211));
  AOI22X1 g11025__4319(.A0 (\fifo[8] [1]), .A1 (n_180), .B0
       (\fifo[7] [1]), .B1 (n_179), .Y (n_208));
  AOI22X1 g11026__8428(.A0 (\fifo[4] [7]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[7]), .Y (n_207));
  AOI22X1 g11028__5526(.A0 (\fifo[5] [0]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[0]), .Y (n_206));
  AOI22X1 g11031__6783(.A0 (\fifo[5] [1]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[1]), .Y (n_205));
  AOI22X1 g11032__3680(.A0 (\fifo[5] [2]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[2]), .Y (n_202));
  AOI22X1 g11033__1617(.A0 (\fifo[5] [3]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[3]), .Y (n_201));
  AOI22X1 g11036__2802(.A0 (\fifo[5] [4]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[4]), .Y (n_200));
  AOI22X1 g11037__1705(.A0 (\fifo[5] [5]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[5]), .Y (n_199));
  AOI22X1 g11038__5122(.A0 (\fifo[5] [6]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[6]), .Y (n_198));
  AOI22X1 g11040__8246(.A0 (\fifo[5] [7]), .A1 (n_204), .B0 (n_203),
       .B1 (data_i[7]), .Y (n_197));
  AOI22X1 g11041__7098(.A0 (\fifo[6] [0]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[0]), .Y (n_196));
  AOI22X1 g11043__6131(.A0 (\fifo[6] [1]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[1]), .Y (n_193));
  AOI22X1 g11044__1881(.A0 (\fifo[6] [2]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[2]), .Y (n_192));
  AOI22X1 g11045__5115(.A0 (\fifo[6] [3]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[3]), .Y (n_191));
  AOI22X1 g11048__7482(.A0 (\fifo[6] [4]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[4]), .Y (n_190));
  AOI22X1 g11021__4733(.A0 (\fifo[4] [4]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[4]), .Y (n_189));
  AOI22X1 g11051__6161(.A0 (\fifo[6] [6]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[6]), .Y (n_188));
  AOI22X1 g11053__9315(.A0 (\fifo[6] [7]), .A1 (n_195), .B0 (n_194),
       .B1 (data_i[7]), .Y (n_187));
  AOI22X1 g11054__9945(.A0 (\fifo[7] [0]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[0]), .Y (n_186));
  AOI22X1 g11057__2883(.A0 (\fifo[7] [1]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[1]), .Y (n_185));
  AOI22X1 g11058__2346(.A0 (\fifo[7] [2]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[2]), .Y (n_182));
  AOI22X1 g11125__1666(.A0 (\fifo[8] [5]), .A1 (n_180), .B0
       (\fifo[7] [5]), .B1 (n_179), .Y (n_181));
  AOI22X1 g11126__7410(.A0 (\fifo[7] [4]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[4]), .Y (n_178));
  AOI22X1 g11127__6417(.A0 (\fifo[7] [5]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[5]), .Y (n_177));
  AOI22X1 g11128__5477(.A0 (\fifo[7] [6]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[6]), .Y (n_176));
  AOI22X1 g11130__2398(.A0 (\fifo[7] [7]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[7]), .Y (n_175));
  AOI22XL g10965__5107(.A0 (\fifo[3] [7]), .A1 (n_162), .B0
       (data_i[7]), .B1 (n_161), .Y (n_174));
  AOI22XL g10966__6260(.A0 (\fifo[0] [5]), .A1 (n_171), .B0
       (data_i[5]), .B1 (n_170), .Y (n_173));
  AOI22XL g10971__4319(.A0 (\fifo[0] [6]), .A1 (n_171), .B0
       (data_i[6]), .B1 (n_170), .Y (n_172));
  AOI22XL g10975__8428(.A0 (\fifo[0] [7]), .A1 (n_171), .B0
       (data_i[7]), .B1 (n_170), .Y (n_169));
  AOI22XL g10977__5526(.A0 (\fifo[1] [0]), .A1 (n_165), .B0
       (data_i[0]), .B1 (n_164), .Y (n_168));
  AOI22X1 g10978__6783(.A0 (\fifo[8] [3]), .A1 (n_180), .B0
       (\fifo[7] [3]), .B1 (n_179), .Y (n_167));
  AOI22XL g10979__3680(.A0 (\fifo[1] [1]), .A1 (n_165), .B0
       (data_i[1]), .B1 (n_164), .Y (n_166));
  AOI22XL g11001__1617(.A0 (\fifo[3] [0]), .A1 (n_162), .B0
       (data_i[0]), .B1 (n_161), .Y (n_163));
  AOI22XL g10980__2802(.A0 (\fifo[1] [2]), .A1 (n_165), .B0
       (data_i[2]), .B1 (n_164), .Y (n_160));
  AOI22XL g10981__1705(.A0 (\fifo[1] [3]), .A1 (n_165), .B0
       (data_i[3]), .B1 (n_164), .Y (n_159));
  AOI22X1 g11165__5122(.A0 (\fifo[8] [2]), .A1 (n_180), .B0
       (\fifo[7] [2]), .B1 (n_179), .Y (n_158));
  AOI22XL g10983__8246(.A0 (\fifo[1] [4]), .A1 (n_165), .B0
       (data_i[4]), .B1 (n_164), .Y (n_157));
  AOI22XL g10984__7098(.A0 (\fifo[1] [5]), .A1 (n_165), .B0
       (data_i[5]), .B1 (n_164), .Y (n_156));
  AOI22XL g10986__6131(.A0 (\fifo[1] [6]), .A1 (n_165), .B0
       (data_i[6]), .B1 (n_164), .Y (n_155));
  AOI22XL g10988__1881(.A0 (\fifo[1] [7]), .A1 (n_165), .B0
       (data_i[7]), .B1 (n_164), .Y (n_154));
  AOI22XL g10989__5115(.A0 (\fifo[2] [0]), .A1 (n_151), .B0
       (data_i[0]), .B1 (n_150), .Y (n_153));
  AOI22XL g10990__7482(.A0 (\fifo[2] [1]), .A1 (n_151), .B0
       (data_i[1]), .B1 (n_150), .Y (n_152));
  AOI22XL g10991__4733(.A0 (\fifo[2] [2]), .A1 (n_151), .B0
       (data_i[2]), .B1 (n_150), .Y (n_149));
  AOI22X1 g11189__6161(.A0 (\fifo[8] [7]), .A1 (n_180), .B0
       (\fifo[7] [7]), .B1 (n_179), .Y (n_148));
  AOI22XL g10994__9315(.A0 (\fifo[2] [3]), .A1 (n_151), .B0
       (data_i[3]), .B1 (n_150), .Y (n_147));
  AOI22XL g10995__9945(.A0 (\fifo[2] [4]), .A1 (n_151), .B0
       (data_i[4]), .B1 (n_150), .Y (n_146));
  AOI22XL g10996__2883(.A0 (\fifo[2] [5]), .A1 (n_151), .B0
       (data_i[5]), .B1 (n_150), .Y (n_145));
  AOI22XL g10998__2346(.A0 (\fifo[2] [6]), .A1 (n_151), .B0
       (data_i[6]), .B1 (n_150), .Y (n_144));
  AOI22XL g11000__1666(.A0 (\fifo[2] [7]), .A1 (n_151), .B0
       (data_i[7]), .B1 (n_150), .Y (n_143));
  AOI22XL g11203__7410(.A0 (\fifo[0] [0]), .A1 (n_171), .B0
       (data_i[0]), .B1 (n_170), .Y (n_142));
  AOI22X1 g11161__6417(.A0 (\fifo[8] [6]), .A1 (n_180), .B0
       (\fifo[7] [6]), .B1 (n_179), .Y (n_141));
  AOI22XL g11004__5477(.A0 (\fifo[3] [1]), .A1 (n_162), .B0
       (data_i[1]), .B1 (n_161), .Y (n_140));
  AOI22X1 g11211__2398(.A0 (\fifo[8] [0]), .A1 (n_180), .B0
       (\fifo[7] [0]), .B1 (n_179), .Y (n_139));
  AOI22XL g11005__5107(.A0 (\fifo[3] [2]), .A1 (n_162), .B0
       (data_i[2]), .B1 (n_161), .Y (n_138));
  AOI22XL g11213__6260(.A0 (\fifo[0] [1]), .A1 (n_171), .B0
       (data_i[1]), .B1 (n_170), .Y (n_137));
  AOI22XL g11007__4319(.A0 (\fifo[3] [3]), .A1 (n_162), .B0
       (data_i[3]), .B1 (n_161), .Y (n_136));
  AOI22XL g11216__8428(.A0 (\fifo[0] [2]), .A1 (n_171), .B0
       (data_i[2]), .B1 (n_170), .Y (n_135));
  AOI22XL g11219__5526(.A0 (\fifo[0] [3]), .A1 (n_171), .B0
       (data_i[3]), .B1 (n_170), .Y (n_134));
  AOI22XL g11009__6783(.A0 (\fifo[3] [4]), .A1 (n_162), .B0
       (data_i[4]), .B1 (n_161), .Y (n_133));
  AOI22X1 g11010__3680(.A0 (\fifo[8] [4]), .A1 (n_180), .B0
       (\fifo[7] [4]), .B1 (n_179), .Y (n_132));
  AOI22XL g11221__1617(.A0 (\fifo[0] [4]), .A1 (n_171), .B0
       (data_i[4]), .B1 (n_170), .Y (n_131));
  AOI22XL g11011__2802(.A0 (\fifo[3] [5]), .A1 (n_162), .B0
       (data_i[5]), .B1 (n_161), .Y (n_130));
  AOI22XL g11012__1705(.A0 (\fifo[3] [6]), .A1 (n_162), .B0
       (data_i[6]), .B1 (n_161), .Y (n_129));
  AOI22X1 g11013__5122(.A0 (\fifo[7] [3]), .A1 (n_184), .B0 (n_183),
       .B1 (data_i[3]), .Y (n_128));
  AOI22X1 g11015__8246(.A0 (\fifo[4] [0]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[0]), .Y (n_127));
  AOI22X1 g11017__7098(.A0 (\fifo[4] [1]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[1]), .Y (n_126));
  AOI22X1 g11019__6131(.A0 (\fifo[4] [2]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[2]), .Y (n_125));
  AOI22X1 g11020__1881(.A0 (\fifo[4] [3]), .A1 (n_210), .B0 (n_209),
       .B1 (data_i[3]), .Y (n_124));
  AOI22X1 g11050__5115(.A0 (\fifo[4] [0]), .A1 (n_121), .B0
       (\fifo[3] [0]), .B1 (n_120), .Y (n_123));
  AOI22X1 g11144__7482(.A0 (\fifo[4] [6]), .A1 (n_121), .B0
       (\fifo[3] [6]), .B1 (n_120), .Y (n_122));
  AOI22X1 g11142__4733(.A0 (\fifo[0] [2]), .A1 (n_116), .B0
       (data_o[2]), .B1 (n_115), .Y (n_119));
  AOI22X1 g11140__6161(.A0 (\fifo[6] [6]), .A1 (n_113), .B0
       (\fifo[5] [6]), .B1 (n_112), .Y (n_118));
  AOI22X1 g11027__9315(.A0 (\fifo[0] [0]), .A1 (n_116), .B0
       (data_o[0]), .B1 (n_115), .Y (n_117));
  AOI22X1 g11030__9945(.A0 (\fifo[6] [5]), .A1 (n_113), .B0
       (\fifo[5] [5]), .B1 (n_112), .Y (n_114));
  AOI22X1 g11035__2883(.A0 (\fifo[4] [5]), .A1 (n_121), .B0
       (\fifo[3] [5]), .B1 (n_120), .Y (n_111));
  AOI22X1 g11039__2346(.A0 (\fifo[0] [5]), .A1 (n_116), .B0
       (data_o[5]), .B1 (n_115), .Y (n_110));
  AOI22X1 g11042__1666(.A0 (\fifo[2] [5]), .A1 (n_105), .B0
       (\fifo[1] [5]), .B1 (n_104), .Y (n_109));
  AOI22X1 g10969__7410(.A0 (\fifo[6] [0]), .A1 (n_113), .B0
       (\fifo[5] [0]), .B1 (n_112), .Y (n_108));
  AOI22X1 g11059__6417(.A0 (\fifo[4] [2]), .A1 (n_121), .B0
       (\fifo[3] [2]), .B1 (n_120), .Y (n_107));
  AOI22X1 g11131__5477(.A0 (\fifo[2] [2]), .A1 (n_105), .B0
       (\fifo[1] [2]), .B1 (n_104), .Y (n_106));
  AOI22X1 g11133__2398(.A0 (\fifo[2] [6]), .A1 (n_105), .B0
       (\fifo[1] [6]), .B1 (n_104), .Y (n_103));
  AOI22X1 g11135__5107(.A0 (\fifo[0] [6]), .A1 (n_116), .B0
       (data_o[6]), .B1 (n_115), .Y (n_102));
  NAND2X1 g11256__6260(.A (n_498), .B (n_78), .Y (n_380));
  NAND2X1 g11257__4319(.A (n_498), .B (n_81), .Y (n_361));
  NAND2X1 g11253__8428(.A (n_498), .B (n_79), .Y (n_388));
  NAND2X1 g11254__5526(.A (n_498), .B (n_75), .Y (n_372));
  AOI22X1 g10999__6783(.A0 (\fifo[0] [1]), .A1 (n_116), .B0
       (data_o[1]), .B1 (n_115), .Y (n_100));
  AOI22X1 g11170__3680(.A0 (\fifo[0] [7]), .A1 (n_116), .B0
       (data_o[7]), .B1 (n_115), .Y (n_99));
  AOI22X1 g10985__1617(.A0 (\fifo[2] [1]), .A1 (n_105), .B0
       (\fifo[1] [1]), .B1 (n_104), .Y (n_98));
  AOI22X1 g11174__2802(.A0 (\fifo[6] [7]), .A1 (n_113), .B0
       (\fifo[5] [7]), .B1 (n_112), .Y (n_97));
  AOI22X1 g11177__1705(.A0 (\fifo[4] [7]), .A1 (n_121), .B0
       (\fifo[3] [7]), .B1 (n_120), .Y (n_96));
  AOI22X1 g11181__5122(.A0 (\fifo[2] [7]), .A1 (n_105), .B0
       (\fifo[1] [7]), .B1 (n_104), .Y (n_95));
  AOI22X1 g10993__8246(.A0 (\fifo[6] [4]), .A1 (n_113), .B0
       (\fifo[5] [4]), .B1 (n_112), .Y (n_94));
  AOI22X1 g10997__7098(.A0 (\fifo[0] [4]), .A1 (n_116), .B0
       (data_o[4]), .B1 (n_115), .Y (n_93));
  AOI22X1 g11199__6131(.A0 (\fifo[4] [3]), .A1 (n_121), .B0
       (\fifo[3] [3]), .B1 (n_120), .Y (n_92));
  AOI22X1 g11146__1881(.A0 (\fifo[6] [2]), .A1 (n_113), .B0
       (\fifo[5] [2]), .B1 (n_112), .Y (n_91));
  AOI22X1 g11201__5115(.A0 (\fifo[2] [0]), .A1 (n_105), .B0
       (\fifo[1] [0]), .B1 (n_104), .Y (n_90));
  AOI22X1 g11002__7482(.A0 (\fifo[4] [4]), .A1 (n_121), .B0
       (\fifo[3] [4]), .B1 (n_120), .Y (n_89));
  AOI22X1 g11003__4733(.A0 (\fifo[6] [1]), .A1 (n_113), .B0
       (\fifo[5] [1]), .B1 (n_112), .Y (n_88));
  AOI22X1 g11207__6161(.A0 (\fifo[0] [3]), .A1 (n_116), .B0
       (data_o[3]), .B1 (n_115), .Y (n_87));
  AOI22X1 g11006__9315(.A0 (\fifo[4] [1]), .A1 (n_121), .B0
       (\fifo[3] [1]), .B1 (n_120), .Y (n_86));
  AOI22X1 g11215__9945(.A0 (\fifo[6] [3]), .A1 (n_113), .B0
       (\fifo[5] [3]), .B1 (n_112), .Y (n_85));
  AOI22X1 g11217__2883(.A0 (\fifo[2] [3]), .A1 (n_105), .B0
       (\fifo[1] [3]), .B1 (n_104), .Y (n_84));
  AOI22X1 g11008__2346(.A0 (\fifo[2] [4]), .A1 (n_105), .B0
       (\fifo[1] [4]), .B1 (n_104), .Y (n_83));
  NOR2X1 g11261__1666(.A (n_72), .B (n_499), .Y (n_332));
  NOR2X1 g11260__7410(.A (n_77), .B (n_499), .Y (n_339));
  NOR2X1 g11249__6417(.A (n_71), .B (n_499), .Y (n_474));
  NAND2BX1 g11262__5477(.AN (n_80), .B (n_81), .Y (n_260));
  NAND2BX1 g11234__2398(.AN (n_80), .B (n_79), .Y (n_233));
  NAND2BX1 g11263__6260(.AN (n_80), .B (n_78), .Y (n_245));
  NOR2BX1 g11244__4319(.AN (n_70), .B (n_499), .Y (n_311));
  NOR2BX1 g11251__5526(.AN (n_73), .B (n_77), .Y (n_333));
  NAND2X1 g11252__6783(.A (n_76), .B (n_79), .Y (n_162));
  NAND2X1 g11258__3680(.A (n_76), .B (n_78), .Y (n_151));
  NAND2X1 g11259__1617(.A (n_76), .B (n_81), .Y (n_165));
  NAND2X1 g11255__2802(.A (n_76), .B (n_75), .Y (n_171));
  NOR2X1 g11281__1705(.A (n_68), .B (n_500), .Y (n_244));
  NOR2X1 g11280__5122(.A (n_62), .B (n_500), .Y (n_259));
  NOR2BX1 g11248__8246(.AN (n_73), .B (n_72), .Y (n_312));
  DFFTRX1 \w_ptr_reg[1] (.CK (clk), .D (n_53), .RN (rst_n), .Q
       (w_ptr[1]), .QN (n_2));
  NOR2X1 g11286__7098(.A (n_66), .B (n_500), .Y (n_232));
  NOR2BX1 g11250__6131(.AN (n_73), .B (n_71), .Y (n_340));
  NAND2X1 g11245__1881(.A (n_69), .B (n_79), .Y (n_184));
  AND2X2 g11231__5115(.A (n_70), .B (n_73), .Y (n_180));
  NAND2X1 g11236__7482(.A (n_69), .B (n_75), .Y (n_210));
  NAND2X1 g11238__4733(.A (n_69), .B (n_81), .Y (n_204));
  NAND2X1 g11239__6161(.A (n_69), .B (n_78), .Y (n_195));
  NOR2X1 g11282__9315(.A (n_59), .B (n_500), .Y (n_270));
  NOR2BX1 g11272__2883(.AN (n_67), .B (n_68), .Y (n_379));
  AND2X2 g11273__2346(.A (n_38), .B (n_67), .Y (n_360));
  DFFTRX1 \r_ptr_reg[0] (.CK (clk), .D (n_49), .RN (rst_n), .Q
       (r_ptr[0]), .QN (n_48));
  NOR2X1 g11247__7410(.A (n_72), .B (n_64), .Y (n_105));
  NOR2BX1 g11270__6417(.AN (n_67), .B (n_66), .Y (n_387));
  NAND2X1 g11266__5477(.A (n_57), .B (n_56), .Y (n_80));
  NOR2X1 g11233__2398(.A (n_77), .B (n_65), .Y (n_112));
  NOR2X1 g11230__5107(.A (n_72), .B (n_65), .Y (n_120));
  NOR2X1 g11232__6260(.A (n_71), .B (n_65), .Y (n_179));
  NOR2BX1 g11235__4319(.AN (n_70), .B (n_65), .Y (n_104));
  NOR2X1 g11237__8428(.A (n_71), .B (n_64), .Y (n_113));
  NOR2BX1 g11240__5526(.AN (n_70), .B (n_64), .Y (n_116));
  NOR2X1 g11246__6783(.A (n_77), .B (n_64), .Y (n_121));
  NOR2X1 g11267__3680(.A (n_55), .B (n_63), .Y (n_69));
  DFFTRX1 \r_ptr_reg[4] (.CK (clk), .D (n_33), .RN (rst_n), .Q
       (r_ptr[4]), .QN (UNCONNECTED));
  DFFTRX1 \r_ptr_reg[1] (.CK (clk), .D (n_32), .RN (rst_n), .Q
       (r_ptr[1]), .QN (n_8));
  NOR2X1 g11269__2802(.A (n_62), .B (n_61), .Y (n_164));
  NOR2X1 g11271__1705(.A (n_66), .B (n_61), .Y (n_161));
  NOR2X1 g11284__5122(.A (n_62), .B (n_60), .Y (n_203));
  NOR2X1 g11287__8246(.A (n_66), .B (n_60), .Y (n_183));
  NOR2X1 g11268__7098(.A (n_59), .B (n_61), .Y (n_170));
  NOR2X1 g11285__6131(.A (n_59), .B (n_60), .Y (n_209));
  NOR2BX1 g11264__1881(.AN (n_56), .B (n_55), .Y (n_76));
  NOR3X1 g11278__5115(.A (r_ptr[0]), .B (n_46), .C (n_51), .Y (n_73));
  DFFTRX1 \w_ptr_reg[4] (.CK (clk), .D (n_31), .RN (rst_n), .Q
       (w_ptr[4]), .QN (UNCONNECTED0));
  DFFTRX1 \w_ptr_reg[3] (.CK (clk), .D (n_34), .RN (rst_n), .Q
       (w_ptr[3]), .QN (n_11));
  DFFTRX1 \w_ptr_reg[0] (.CK (clk), .D (n_44), .RN (rst_n), .Q
       (w_ptr[0]), .QN (n_3));
  DFFTRX1 \w_ptr_reg[2] (.CK (clk), .D (n_35), .RN (rst_n), .Q
       (w_ptr[2]), .QN (UNCONNECTED1));
  DFFTRX1 \r_ptr_reg[3] (.CK (clk), .D (n_40), .RN (rst_n), .Q
       (r_ptr[3]), .QN (UNCONNECTED2));
  DFFTRX1 \r_ptr_reg[2] (.CK (clk), .D (n_42), .RN (rst_n), .Q
       (r_ptr[2]), .QN (n_1));
  NOR2X1 g11283__7482(.A (n_68), .B (n_60), .Y (n_194));
  NOR2X1 g11274__4733(.A (n_68), .B (n_61), .Y (n_150));
  NAND3X1 g11276__6161(.A (n_48), .B (n_54), .C (rst_n), .Y (n_64));
  NAND3X1 g11277__9315(.A (r_ptr[0]), .B (n_54), .C (rst_n), .Y (n_65));
  OAI2BB1X1 g11290__9945(.A0N (n_43), .A1N (w_ptr[1]), .B0 (n_39), .Y
       (n_53));
  NAND2X1 g11291__2883(.A (n_52), .B (rst_n), .Y (n_57));
  NOR2X1 g11293__2346(.A (n_52), .B (n_56), .Y (n_67));
  NOR2X1 g11292__1666(.A (n_50), .B (n_51), .Y (n_55));
  NAND2X1 g11296__7410(.A (n_50), .B (n_63), .Y (n_61));
  NAND2BX1 g11294__6417(.AN (n_56), .B (n_50), .Y (n_60));
  OAI22XL g11300__5477(.A0 (r_ptr[0]), .A1 (n_41), .B0 (n_48), .B1
       (n_37), .Y (n_49));
  OAI2BB2XL g11303__2398(.A0N (n_43), .A1N (w_ptr[0]), .B0 (w_ptr[0]),
       .B1 (n_43), .Y (n_44));
  OAI2BB2XL g11298__5107(.A0N (n_41), .A1N (r_ptr[2]), .B0 (n_20), .B1
       (n_41), .Y (n_42));
  OAI2BB2XL g11299__6260(.A0N (n_41), .A1N (r_ptr[3]), .B0 (n_19), .B1
       (n_41), .Y (n_40));
  OAI21XL g11310__4319(.A0 (n_4), .A1 (n_38), .B0 (n_36), .Y (n_39));
  NAND2X1 g11307__8428(.A (r_ptr[3]), .B (n_37), .Y (n_46));
  NAND2X1 g11311__5526(.A (w_ptr[3]), .B (n_36), .Y (n_52));
  OAI2BB2XL g11289__6783(.A0N (n_43), .A1N (w_ptr[2]), .B0 (n_18), .B1
       (n_43), .Y (n_35));
  OAI2BB2XL g11301__3680(.A0N (n_43), .A1N (w_ptr[3]), .B0 (n_24), .B1
       (n_43), .Y (n_34));
  OAI2BB2XL g11302__1617(.A0N (n_41), .A1N (r_ptr[4]), .B0 (n_23), .B1
       (n_41), .Y (n_33));
  OAI2BB2XL g11304__2802(.A0N (n_41), .A1N (r_ptr[1]), .B0 (n_9), .B1
       (n_41), .Y (n_32));
  OAI2BB2XL g11243__1705(.A0N (n_43), .A1N (w_ptr[4]), .B0 (n_28), .B1
       (n_43), .Y (n_31));
  NOR2X1 g11312__5122(.A (n_37), .B (n_51), .Y (n_115));
  NOR2X1 g11308__8246(.A (w_ptr[3]), .B (n_43), .Y (n_50));
  NOR2X1 g11306__7098(.A (r_ptr[3]), .B (n_41), .Y (n_54));
  INVX1 g11313(.A (n_41), .Y (n_37));
  INVX1 g11315(.A (n_43), .Y (n_36));
  NAND2BX1 g11317__6131(.AN (full), .B (we), .Y (n_43));
  NAND2BX1 g11314__1881(.AN (empty), .B (re), .Y (n_41));
  AOI2BB2X1 g11297__5115(.A0N (n_27), .A1N (w_ptr[4]), .B0 (n_27), .B1
       (w_ptr[4]), .Y (n_28));
  NOR2BXL g11320__7482(.AN (n_26), .B (n_25), .Y (empty));
  AND2X2 g11318__4733(.A (n_26), .B (n_25), .Y (full));
  OAI21XL g11319__6161(.A0 (n_21), .A1 (w_ptr[3]), .B0 (n_27), .Y
       (n_24));
  AOI2BB2X1 g11316__9315(.A0N (n_22), .A1N (r_ptr[4]), .B0 (n_22), .B1
       (r_ptr[4]), .Y (n_23));
  AOI211XL g11322__9945(.A0 (n_11), .A1 (r_ptr[3]), .B0 (n_14), .C0
       (n_12), .Y (n_26));
  NAND2X1 g11321__2883(.A (n_21), .B (w_ptr[3]), .Y (n_27));
  AOI221X1 g11323__2346(.A0 (n_6), .A1 (r_ptr[0]), .B0 (n_48), .B1
       (r_ptr[2]), .C0 (n_5), .Y (n_20));
  OAI21XL g11324__1666(.A0 (n_16), .A1 (r_ptr[3]), .B0 (n_22), .Y
       (n_19));
  OAI21XL g11327__7410(.A0 (n_13), .A1 (w_ptr[2]), .B0 (n_17), .Y
       (n_18));
  INVX1 g11329(.A (n_17), .Y (n_21));
  NAND2X1 g11326__6417(.A (n_16), .B (r_ptr[3]), .Y (n_22));
  OAI221XL g11325__5477(.A0 (n_48), .A1 (w_ptr[0]), .B0 (n_3), .B1
       (r_ptr[0]), .C0 (n_497), .Y (n_14));
  NAND2X1 g11332__2398(.A (n_13), .B (w_ptr[2]), .Y (n_17));
  NAND2X1 g11334__5107(.A (n_59), .B (rst_n), .Y (n_75));
  OAI222XL g11328__6260(.A0 (n_8), .A1 (w_ptr[1]), .B0 (n_11), .B1
       (r_ptr[3]), .C0 (r_ptr[1]), .C1 (n_2), .Y (n_12));
  NAND2X1 g11339__4319(.A (n_62), .B (rst_n), .Y (n_81));
  NAND2X1 g11338__8428(.A (n_68), .B (rst_n), .Y (n_78));
  AOI22X1 g11336__5526(.A0 (r_ptr[0]), .A1 (n_8), .B0 (n_48), .B1
       (r_ptr[1]), .Y (n_9));
  INVX1 g11348(.A (n_72), .Y (n_6));
  INVX1 g11347(.A (n_77), .Y (n_5));
  INVXL g11350(.A (n_68), .Y (n_4));
  NOR2X1 g11331__3680(.A (n_71), .B (n_48), .Y (n_16));
  INVX1 g11349(.A (n_62), .Y (n_38));
  NAND2X1 g11333__1617(.A (n_66), .B (rst_n), .Y (n_79));
  NAND2X1 g11345__2802(.A (n_3), .B (n_2), .Y (n_59));
  NAND2X1 g11354__1705(.A (n_2), .B (w_ptr[0]), .Y (n_62));
  NAND2X1 g11352__5122(.A (n_8), .B (r_ptr[2]), .Y (n_77));
  NAND2X1 g11355__8246(.A (n_3), .B (w_ptr[1]), .Y (n_68));
  AOI2BB2X1 g11337__7098(.A0N (r_ptr[4]), .A1N (w_ptr[4]), .B0
       (r_ptr[4]), .B1 (w_ptr[4]), .Y (n_25));
  INVX1 g11341(.A (n_66), .Y (n_13));
  NOR2X1 g11351__6131(.A (w_ptr[2]), .B (n_51), .Y (n_63));
  NAND2X1 g11353__1881(.A (n_1), .B (r_ptr[1]), .Y (n_72));
  NOR2X1 g11343__5115(.A (r_ptr[2]), .B (r_ptr[1]), .Y (n_70));
  NAND2X1 g11346__7482(.A (w_ptr[0]), .B (w_ptr[1]), .Y (n_66));
  NAND2X1 g11342__4733(.A (w_ptr[2]), .B (rst_n), .Y (n_56));
  NAND2X1 g11344__6161(.A (r_ptr[2]), .B (r_ptr[1]), .Y (n_71));
  INVXL g11363(.A (rst_n), .Y (n_51));
  MXI2XL g2(.S0 (w_ptr[2]), .B (n_1), .A (r_ptr[2]), .Y (n_497));
  NOR2BX1 g11510(.AN (n_57), .B (n_63), .Y (n_498));
  NAND3BX1 g11511(.AN (n_46), .B (r_ptr[0]), .C (rst_n), .Y (n_499));
  NAND2BX1 g11512(.AN (n_52), .B (n_63), .Y (n_500));
  NAND2BX1 g11513(.AN (n_80), .B (n_75), .Y (n_501));
  NOR2BX1 g11514(.AN (n_67), .B (n_59), .Y (n_502));
endmodule

